### ISSUE TITLE
[FR] Full support for OSB Context + originating-identity-header in request variable

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/cloud-service-broker#138]
**Is your feature request related to a problem? Please describe.**

As a brokerpak author
* in order to apply some processing depending on OSB client metadata (such as opening network ACLs depending on caller, or recording audit traces for caller metadata such as  `organization_name`, `space_name`, `instance_name` or K8S `namespace`)
* I need [Osb context](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) and [Originating Identity Header](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#originating-identity-header) to be exposed to brokerpak Terraform templates

**Describe the solution you'd like**

A new `request.context` field in the existing [request](https://github.com/pivotal/cloud-service-broker/blob/master/docs/brokerpak-specification.md#provision) variable. This field would contain the full context JSON object as a map, including the `platform` field with values among `cloudfoundry` and `kubernetes`

A new `request.x_broker_api_originating_identity` field in the existing [request](https://github.com/pivotal/cloud-service-broker/blob/master/docs/brokerpak-specification.md#provision) variable. This field would contain the base64 decoded full JSON object as a map, eg.

for cloudfoundry

```json
{
  "user_id": "683ea748-3092-4ff4-b656-39cacc4d5360"
}
```

and for K8S:

```json
{
  "username": "duke",
  "uid": "c2dde242-5ce4-11e7-988c-000c2946f14f",
  "groups": [ "admin", "dev" ],
  "extra": {
    "mydata": [ "data1", "data3" ]
  }
}
```

**Describe alternatives you've considered**

The existing `request.default_labels` are exposing and mapping part of the [Osb context](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for cloudfoundry but are missing 
* the [kubernetes profile](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#kubernetes-context-object) fields such as namespace
* the [cloud foundry profile](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-context-object) fields `organization_name`, `space_name`, `instance_name`, 

**Additional Context**

**Priority**

**Priority Context**

**Platform** 

**Applicable Services**

/CC @mlesaout

**Comment by omerbensaadon** [comment]
@gberche-orange We have marked this issues as "help wanted" which means we are seeking contributions to help close out this issue. Unfortunately, not a top priority for the team at the moment, please let us know how we can assist. 

CC: @erniebilling @svennela

**Comment by gberche-orange** [comment]
thanks @omerbensaadon for reviewing this suggestion. 

My team might be able to contribute this support in the future. Graduating the project as a Cloud Foundry Foundation project will certainly foster our contributions to the project. Any chance to progress on this topic (related [slack thread](https://cloudfoundry.slack.com/archives/C36KPCW15/p1606809613023300?thread_ts=1606158513.022200&cid=C36KPCW15) available for community interest) ?

**Comment by omerbensaadon** [comment]
@gberche-orange Looks like we were accepted! Speaking with someone from the CF Extension team today 👍🏼

**Comment by gberche-orange** [comment]
awesome, thanks @omerbensaadon !

**Comment by pivotal-marcela-campo** [comment]
@gberche-orange We took a shot at implementing this functionality for provision/deprovision. Would you mind taking a look at the PR and checking that's what you were expecting? If so we can add to bind/unbind as well.

Thanks!

**Comment by gberche-orange** [comment]
thanks a lot @pivotal-marcela-campo ! I plan to review PR by monday.

**Comment by gberche-orange** [comment]
@pivotal-marcela-campo 

>  Would you mind taking a look at the PR and checking that's what you were expecting? If so we can add to bind/unbind as well.

This perfectly matches my use-case. Thanks ! 

This would be great to have the same for bind/unbind, and possibly [update service instance](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-6)

**Comment by omerbensaadon** [comment]
Glad to see some movement on this! Thank you @pivotal-marcela-campo :)

**Comment by pivotal-marcela-campo** [comment]
This has been implemented and available to use from any custom brokerpak. Closing.
