### ISSUE TITLE
[BUG] Azure SQL bind/unbind operations fail for existing instances after SQL admin password is changed

### ISSUE THREAD

**Issue by claassen** [cloudfoundry-incubator/cloud-service-broker#158]
## Description
After changing the SQL admin password and re-deploying the broker, bind and unbind operations for existing database instances fail due to invalid credentials. It appears the broker stores and is trying to use the SQL admin password that was used when the service instance was created rather than the password that the broker is currently configured to use.

## Expected Behavior
The broker should use the current password as configured rather than the password that was used when the instance was created for bind/unbind (and potentially other) operations.

## Actual Behavior
```
An unbind operation for the service binding between app csb-synthetic-probes and service instance csb-azuresql-probe failed: Service broker error: Error: Error running command 'psqlcmd azugessqlsandbox.database.windows.net 1433 gessqladmin <old password that is now wrong> csb-db-0e9e08b0-64f8-4432-a526-4613ed5b5a5a "ALTER ROLE db_ddladmin DROP MEMBER [JTNWBRCkNmubbVhC]"': exit status 1. Output: 2020/12/11 22:52:14 Login error: mssql: Login failed for user 'gessqladmin'.Error: Error running command 'psqlcmd azugessqlsandbox.database.windows.net 1433 gessqladmin <old password that is now wrong> csb-db-0e9e08b0-64f8-4432-a526-4613ed5b5a5a "ALTER ROLE db_datawriter DROP MEMBER [JTNWBRCkNmubbVhC]"': exit status 1. Output: 2020/12/11 22:52:14 Login error: mssql: Login failed for user 'gessqladmin'.Error: Error running command 'psqlcmd azugessqlsandbox.database.windows.net 1433 gessqladmin <old password that is now wrong> csb-db-0e9e08b0-64f8-4432-a526-4613ed5b5a5a "ALTER ROLE db_datareader DROP MEMBER [JTNWBRCkNmubbVhC]"': exit status 1. Output: 2020/12/11 22:52:14 Login error: mssql: Login failed for user 'gessqladmin'. exit status 1
```

## Possible Fix
Make broker use current configured password for all operations. I am not 100% sure, but I suspect that operations on existing instances are using the username/password stored in the other_details field of the service_instance_details table.

## Steps to Reproduce
1. Configure broker with SQL admin password A
2. Create instance
3. Change SQL admin password to B
4. Re-deploy broker with new password
5. Perform bind or unbind operation on existing instance

## Context
This behaviour means we do not have the ability to rotate the SQL admin password without breaking operations on existing instances.

## Your Environment
* Version used: sb-0.2.1-rc.4-azure-1.0.0-rc.27
* Platform (Azure/AWS/GCP): Azure
* Applicable Services: csb-azure-mssql-db, csb-azure-mssql-db-failover-group

**Comment by erniebilling** [comment]
You are correct @claassen The broker uses the credentials provided or created during provision for the bind/unbind operations. We'll investigate possible solutions and prioritize a fix.

**Comment by claassen** [comment]
Just FYI, we were able work around the issue temporarily by executing the following on the broker database:

```
update service_instance_details
set other_details = REPLACE(other_details, N'<old password>', '<new password>')

update terraform_deployments
set workspace = REPLACE(workspace, N'<old password>', '<new password>')
```

**Comment by claassen** [comment]
Also wondering if this will be an issue with azure_client_id and azure_client_secret, which we will also need to rotate.

**Comment by erniebilling** [comment]
> Also wondering if this will be an issue with azure_client_id and azure_client_secret, which we will also need to rotate.

Not on bind/unbind in this particular case since the Azure provider isn't used, so those creds won't come in to play. But will test deprovision.

**Comment by claassen** [comment]
Saw some commits that look related to this fix, is this issue fixed now, or at least ready to be tested?

**Comment by erniebilling** [comment]
Azure brokerpak now supports a new config values (`azure.mssql_db_server_creds` and `azure.mssql_db_fog_server_pair_creds`) see docs [here](https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/master/docs/mssql-db-plans-and-config.md#configuring-global-defaults) and [here](https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/master/docs/mssql-db-fog-config.md#configuring-global-defaults) for server credentials. This approach allows them to be resolved from the environment when the broker is started instead of being resolved from the results of the service provisioning.

Tile release 1.1.7 configures the proper environment values.
